/* Auto-generated by genmsg_cpp for file /home/parth/Code/ME597/RobotCode/clearpath_horizon/msg/AckermannSetpt.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_ACKERMANNSETPT_H
#define CLEARPATH_HORIZON_MESSAGE_ACKERMANNSETPT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace clearpath_horizon
{
template <class ContainerAllocator>
struct AckermannSetpt_ {
  typedef AckermannSetpt_<ContainerAllocator> Type;

  AckermannSetpt_()
  : header()
  , steering(0.0)
  , throttle(0.0)
  , brake(0.0)
  {
  }

  AckermannSetpt_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , steering(0.0)
  , throttle(0.0)
  , brake(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _steering_type;
  double steering;

  typedef double _throttle_type;
  double throttle;

  typedef double _brake_type;
  double brake;


  typedef boost::shared_ptr< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AckermannSetpt
typedef  ::clearpath_horizon::AckermannSetpt_<std::allocator<void> > AckermannSetpt;

typedef boost::shared_ptr< ::clearpath_horizon::AckermannSetpt> AckermannSetptPtr;
typedef boost::shared_ptr< ::clearpath_horizon::AckermannSetpt const> AckermannSetptConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "46d60e86aa5967736d40185bb6efb208";
  }

  static const char* value(const  ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x46d60e86aa596773ULL;
  static const uint64_t static_value2 = 0x6d40185bb6efb208ULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/AckermannSetpt";
  }

  static const char* value(const  ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 steering\n\
float64 throttle\n\
float64 brake\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.steering);
    stream.next(m.throttle);
    stream.next(m.brake);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AckermannSetpt_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::AckermannSetpt_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "brake: ";
    Printer<double>::stream(s, indent + "  ", v.brake);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_ACKERMANNSETPT_H

