/* Auto-generated by genmsg_cpp for file /home/wavelab/TeamAwesome/ME597/RobotCode/clearpath_horizon/msg/DifferentialOutput.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_DIFFERENTIALOUTPUT_H
#define CLEARPATH_HORIZON_MESSAGE_DIFFERENTIALOUTPUT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace clearpath_horizon
{
template <class ContainerAllocator>
struct DifferentialOutput_ {
  typedef DifferentialOutput_<ContainerAllocator> Type;

  DifferentialOutput_()
  : header()
  , left(0.0)
  , right(0.0)
  {
  }

  DifferentialOutput_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , left(0.0)
  , right(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _left_type;
  double left;

  typedef double _right_type;
  double right;


  typedef boost::shared_ptr< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DifferentialOutput
typedef  ::clearpath_horizon::DifferentialOutput_<std::allocator<void> > DifferentialOutput;

typedef boost::shared_ptr< ::clearpath_horizon::DifferentialOutput> DifferentialOutputPtr;
typedef boost::shared_ptr< ::clearpath_horizon::DifferentialOutput const> DifferentialOutputConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8f32685125452f5bdf68130369af5296";
  }

  static const char* value(const  ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8f32685125452f5bULL;
  static const uint64_t static_value2 = 0xdf68130369af5296ULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/DifferentialOutput";
  }

  static const char* value(const  ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 left\n\
float64 right\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.left);
    stream.next(m.right);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DifferentialOutput_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::DifferentialOutput_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_DIFFERENTIALOUTPUT_H

