/* Auto-generated by genmsg_cpp for file /home/wavelab/TeamAwesome/ME597/RobotCode/clearpath_horizon/msg/Encoder.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_ENCODER_H
#define CLEARPATH_HORIZON_MESSAGE_ENCODER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace clearpath_horizon
{
template <class ContainerAllocator>
struct Encoder_ {
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
  : travel(0.0)
  , speed(0.0)
  {
  }

  Encoder_(const ContainerAllocator& _alloc)
  : travel(0.0)
  , speed(0.0)
  {
  }

  typedef double _travel_type;
  double travel;

  typedef double _speed_type;
  double speed;


  typedef boost::shared_ptr< ::clearpath_horizon::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::Encoder_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Encoder
typedef  ::clearpath_horizon::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::clearpath_horizon::Encoder> EncoderPtr;
typedef boost::shared_ptr< ::clearpath_horizon::Encoder const> EncoderConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::Encoder_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::Encoder_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::Encoder_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::Encoder_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "620a74fe7e8deb0e96bf85b534453633";
  }

  static const char* value(const  ::clearpath_horizon::Encoder_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x620a74fe7e8deb0eULL;
  static const uint64_t static_value2 = 0x96bf85b534453633ULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/Encoder";
  }

  static const char* value(const  ::clearpath_horizon::Encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 travel\n\
float64 speed\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::Encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::clearpath_horizon::Encoder_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::Encoder_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.travel);
    stream.next(m.speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Encoder_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::Encoder_<ContainerAllocator> & v) 
  {
    s << indent << "travel: ";
    Printer<double>::stream(s, indent + "  ", v.travel);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_ENCODER_H

