/* Auto-generated by genmsg_cpp for file /home/wavelab/TeamAwesome/ME597/RobotCode/clearpath_horizon/msg/FirmwareInfo.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_FIRMWAREINFO_H
#define CLEARPATH_HORIZON_MESSAGE_FIRMWAREINFO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace clearpath_horizon
{
template <class ContainerAllocator>
struct FirmwareInfo_ {
  typedef FirmwareInfo_<ContainerAllocator> Type;

  FirmwareInfo_()
  : header()
  , firmware_major(0)
  , firmware_minor(0)
  , protocol_major(0)
  , protocol_minor(0)
  , firmware_write_time(0)
  {
  }

  FirmwareInfo_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , firmware_major(0)
  , firmware_minor(0)
  , protocol_major(0)
  , protocol_minor(0)
  , firmware_write_time(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int8_t _firmware_major_type;
  int8_t firmware_major;

  typedef int8_t _firmware_minor_type;
  int8_t firmware_minor;

  typedef int8_t _protocol_major_type;
  int8_t protocol_major;

  typedef int8_t _protocol_minor_type;
  int8_t protocol_minor;

  typedef uint32_t _firmware_write_time_type;
  uint32_t firmware_write_time;


  typedef boost::shared_ptr< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FirmwareInfo
typedef  ::clearpath_horizon::FirmwareInfo_<std::allocator<void> > FirmwareInfo;

typedef boost::shared_ptr< ::clearpath_horizon::FirmwareInfo> FirmwareInfoPtr;
typedef boost::shared_ptr< ::clearpath_horizon::FirmwareInfo const> FirmwareInfoConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dd399eb9c7b3816e8bea664a45a7e9ea";
  }

  static const char* value(const  ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdd399eb9c7b3816eULL;
  static const uint64_t static_value2 = 0x8bea664a45a7e9eaULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/FirmwareInfo";
  }

  static const char* value(const  ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int8 firmware_major\n\
int8 firmware_minor\n\
int8 protocol_major\n\
int8 protocol_minor\n\
uint32 firmware_write_time\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.firmware_major);
    stream.next(m.firmware_minor);
    stream.next(m.protocol_major);
    stream.next(m.protocol_minor);
    stream.next(m.firmware_write_time);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FirmwareInfo_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::FirmwareInfo_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "firmware_major: ";
    Printer<int8_t>::stream(s, indent + "  ", v.firmware_major);
    s << indent << "firmware_minor: ";
    Printer<int8_t>::stream(s, indent + "  ", v.firmware_minor);
    s << indent << "protocol_major: ";
    Printer<int8_t>::stream(s, indent + "  ", v.protocol_major);
    s << indent << "protocol_minor: ";
    Printer<int8_t>::stream(s, indent + "  ", v.protocol_minor);
    s << indent << "firmware_write_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.firmware_write_time);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_FIRMWAREINFO_H

