/* Auto-generated by genmsg_cpp for file /home/parth/Code/ME597/RobotCode/clearpath_horizon/msg/Joy.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_JOY_H
#define CLEARPATH_HORIZON_MESSAGE_JOY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace clearpath_horizon
{
template <class ContainerAllocator>
struct Joy_ {
  typedef Joy_<ContainerAllocator> Type;

  Joy_()
  : axes()
  , buttons()
  {
  }

  Joy_(const ContainerAllocator& _alloc)
  : axes(_alloc)
  , buttons(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _axes_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  axes;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _buttons_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  buttons;


  typedef boost::shared_ptr< ::clearpath_horizon::Joy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::Joy_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Joy
typedef  ::clearpath_horizon::Joy_<std::allocator<void> > Joy;

typedef boost::shared_ptr< ::clearpath_horizon::Joy> JoyPtr;
typedef boost::shared_ptr< ::clearpath_horizon::Joy const> JoyConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::Joy_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::Joy_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::Joy_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::Joy_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::Joy_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e3ef016fcdf22397038b36036c66f7c8";
  }

  static const char* value(const  ::clearpath_horizon::Joy_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe3ef016fcdf22397ULL;
  static const uint64_t static_value2 = 0x038b36036c66f7c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::Joy_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/Joy";
  }

  static const char* value(const  ::clearpath_horizon::Joy_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::Joy_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[] axes\n\
int32[] buttons\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::Joy_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::Joy_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.axes);
    stream.next(m.buttons);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Joy_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::Joy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::Joy_<ContainerAllocator> & v) 
  {
    s << indent << "axes[]" << std::endl;
    for (size_t i = 0; i < v.axes.size(); ++i)
    {
      s << indent << "  axes[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.axes[i]);
    }
    s << indent << "buttons[]" << std::endl;
    for (size_t i = 0; i < v.buttons.size(); ++i)
    {
      s << indent << "  buttons[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.buttons[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_JOY_H

