/* Auto-generated by genmsg_cpp for file /home/parth/Code/ME597/RobotCode/clearpath_horizon/msg/PlatformName.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_PLATFORMNAME_H
#define CLEARPATH_HORIZON_MESSAGE_PLATFORMNAME_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace clearpath_horizon
{
template <class ContainerAllocator>
struct PlatformName_ {
  typedef PlatformName_<ContainerAllocator> Type;

  PlatformName_()
  : header()
  , name()
  {
  }

  PlatformName_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , name(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;


  typedef boost::shared_ptr< ::clearpath_horizon::PlatformName_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::PlatformName_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PlatformName
typedef  ::clearpath_horizon::PlatformName_<std::allocator<void> > PlatformName;

typedef boost::shared_ptr< ::clearpath_horizon::PlatformName> PlatformNamePtr;
typedef boost::shared_ptr< ::clearpath_horizon::PlatformName const> PlatformNameConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::PlatformName_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::PlatformName_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::PlatformName_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::PlatformName_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::PlatformName_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e541bb76a27a3e03e7987c32ec4fd724";
  }

  static const char* value(const  ::clearpath_horizon::PlatformName_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe541bb76a27a3e03ULL;
  static const uint64_t static_value2 = 0xe7987c32ec4fd724ULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::PlatformName_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/PlatformName";
  }

  static const char* value(const  ::clearpath_horizon::PlatformName_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::PlatformName_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
string name\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::PlatformName_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::clearpath_horizon::PlatformName_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::clearpath_horizon::PlatformName_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::PlatformName_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.name);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PlatformName_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::PlatformName_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::PlatformName_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_PLATFORMNAME_H

