/* Auto-generated by genmsg_cpp for file /home/parth/Code/ME597/RobotCode/clearpath_horizon/msg/ProcessorStatus.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_PROCESSORSTATUS_H
#define CLEARPATH_HORIZON_MESSAGE_PROCESSORSTATUS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace clearpath_horizon
{
template <class ContainerAllocator>
struct ProcessorStatus_ {
  typedef ProcessorStatus_<ContainerAllocator> Type;

  ProcessorStatus_()
  : header()
  , errors()
  {
  }

  ProcessorStatus_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , errors(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _errors_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  errors;


  typedef boost::shared_ptr< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ProcessorStatus
typedef  ::clearpath_horizon::ProcessorStatus_<std::allocator<void> > ProcessorStatus;

typedef boost::shared_ptr< ::clearpath_horizon::ProcessorStatus> ProcessorStatusPtr;
typedef boost::shared_ptr< ::clearpath_horizon::ProcessorStatus const> ProcessorStatusConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9d74dc2afa1a3a812e1ca5482185d3cf";
  }

  static const char* value(const  ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9d74dc2afa1a3a81ULL;
  static const uint64_t static_value2 = 0x2e1ca5482185d3cfULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/ProcessorStatus";
  }

  static const char* value(const  ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32[] errors\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.errors);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ProcessorStatus_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::ProcessorStatus_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "errors[]" << std::endl;
    for (size_t i = 0; i < v.errors.size(); ++i)
    {
      s << indent << "  errors[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.errors[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_PROCESSORSTATUS_H

