/* Auto-generated by genmsg_cpp for file /home/wavelab/TeamAwesome/ME597/RobotCode/clearpath_horizon/msg/VelocitySetpt.msg */
#ifndef CLEARPATH_HORIZON_MESSAGE_VELOCITYSETPT_H
#define CLEARPATH_HORIZON_MESSAGE_VELOCITYSETPT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace clearpath_horizon
{
template <class ContainerAllocator>
struct VelocitySetpt_ {
  typedef VelocitySetpt_<ContainerAllocator> Type;

  VelocitySetpt_()
  : header()
  , trans_vel(0.0)
  , rot_vel(0.0)
  , trans_accel(0.0)
  {
  }

  VelocitySetpt_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , trans_vel(0.0)
  , rot_vel(0.0)
  , trans_accel(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _trans_vel_type;
  double trans_vel;

  typedef double _rot_vel_type;
  double rot_vel;

  typedef double _trans_accel_type;
  double trans_accel;


  typedef boost::shared_ptr< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct VelocitySetpt
typedef  ::clearpath_horizon::VelocitySetpt_<std::allocator<void> > VelocitySetpt;

typedef boost::shared_ptr< ::clearpath_horizon::VelocitySetpt> VelocitySetptPtr;
typedef boost::shared_ptr< ::clearpath_horizon::VelocitySetpt const> VelocitySetptConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clearpath_horizon

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "749b7f1446a3381cca62b6e10023c1de";
  }

  static const char* value(const  ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x749b7f1446a3381cULL;
  static const uint64_t static_value2 = 0xca62b6e10023c1deULL;
};

template<class ContainerAllocator>
struct DataType< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clearpath_horizon/VelocitySetpt";
  }

  static const char* value(const  ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 trans_vel\n\
float64 rot_vel\n\
float64 trans_accel\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.trans_vel);
    stream.next(m.rot_vel);
    stream.next(m.trans_accel);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct VelocitySetpt_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clearpath_horizon::VelocitySetpt_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "trans_vel: ";
    Printer<double>::stream(s, indent + "  ", v.trans_vel);
    s << indent << "rot_vel: ";
    Printer<double>::stream(s, indent + "  ", v.rot_vel);
    s << indent << "trans_accel: ";
    Printer<double>::stream(s, indent + "  ", v.trans_accel);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLEARPATH_HORIZON_MESSAGE_VELOCITYSETPT_H

